#ifndef U_INSIGHT_H
#define U_INSIGHT_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Error codes returned by FFI functions.
 */
#define INSIGHT_OK 0

#define INSIGHT_ERR_NULL_PTR -1

#define INSIGHT_ERR_INVALID_INPUT -2

#define INSIGHT_ERR_PARSE_FAILED -3

#define INSIGHT_ERR_ANALYSIS_FAILED -4

#define INSIGHT_ERR_PANIC -99

#define INSIGHT_ERR_INSUFFICIENT_DATA -5

#define INSIGHT_ERR_INVALID_PARAM -6

#define INSIGHT_ERR_DEGENERATE_DATA -7

#define INSIGHT_ERR_COMPUTATION_FAILED -8

/**
 * Opaque handle for a profiling context.
 * Holds the parsed DataFrame and computed profiles.
 */
typedef struct ProfileContext ProfileContext;

/**
 * C-compatible column profile summary.
 */
typedef struct CColumnSummary {
  /**
   * Column index.
   */
  uint32_t index;
  /**
   * Number of valid (non-null) values.
   */
  uint64_t valid_count;
  /**
   * Number of null values.
   */
  uint64_t null_count;
  /**
   * Column data type: 0=Numeric, 1=Boolean, 2=Categorical, 3=Text.
   */
  uint32_t data_type;
  /**
   * For numeric columns: mean. NaN for non-numeric.
   */
  double mean;
  /**
   * For numeric columns: standard deviation. NaN for non-numeric.
   */
  double std_dev;
  /**
   * For numeric columns: minimum. NaN for non-numeric.
   */
  double min;
  /**
   * For numeric columns: maximum. NaN for non-numeric.
   */
  double max;
} CColumnSummary;

/**
 * C-compatible K-Means result.
 */
typedef struct CKMeansResult {
  /**
   * Number of clusters.
   */
  uint32_t k;
  /**
   * WCSS value.
   */
  double wcss;
  /**
   * Number of iterations.
   */
  uint32_t iterations;
  /**
   * Cluster labels (length = n_rows). Caller must free with `insight_free_labels`.
   */
  uint32_t *labels;
  /**
   * Number of labels.
   */
  uint32_t n_labels;
} CKMeansResult;

/**
 * C-compatible PCA result.
 */
typedef struct CPcaResult {
  /**
   * Number of components retained.
   */
  uint32_t n_components;
  /**
   * Explained variance ratios (length = n_components).
   * Caller must free with `insight_free_f64_array`.
   */
  double *explained_variance;
  /**
   * Number of variance values.
   */
  uint32_t n_variance;
} CPcaResult;

/**
 * C-compatible DBSCAN result.
 */
typedef struct CDbscanResult {
  /**
   * Number of clusters discovered.
   */
  uint32_t n_clusters;
  /**
   * Number of noise points.
   */
  uint32_t noise_count;
  /**
   * Cluster labels (length = n_rows). -1 = noise, >= 0 = cluster id.
   * Caller must free with `insight_free_i32_array`.
   */
  int32_t *labels;
  /**
   * Number of labels.
   */
  uint32_t n_labels;
} CDbscanResult;

/**
 * C-compatible distribution analysis result (normality assessment).
 */
typedef struct CDistributionResult {
  /**
   * Number of observations.
   */
  uint32_t n;
  /**
   * KS test statistic (NaN if unavailable).
   */
  double ks_statistic;
  /**
   * KS test p-value (NaN if unavailable).
   */
  double ks_p_value;
  /**
   * Jarque-Bera test statistic (NaN if unavailable).
   */
  double jb_statistic;
  /**
   * Jarque-Bera test p-value (NaN if unavailable).
   */
  double jb_p_value;
  /**
   * Shapiro-Wilk W statistic (NaN if unavailable).
   */
  double sw_statistic;
  /**
   * Shapiro-Wilk p-value (NaN if unavailable).
   */
  double sw_p_value;
  /**
   * Anderson-Darling A*² statistic (NaN if unavailable).
   */
  double ad_statistic;
  /**
   * Anderson-Darling p-value (NaN if unavailable).
   */
  double ad_p_value;
  /**
   * Whether data appears normally distributed. 1 = normal, 0 = not normal.
   */
  int32_t is_normal;
} CDistributionResult;

/**
 * C-compatible feature importance result.
 */
typedef struct CFeatureImportanceResult {
  /**
   * Importance scores per feature (length = n_cols). Higher = more important.
   * Caller must free with `insight_free_f64_array`.
   */
  double *scores;
  /**
   * Number of scores.
   */
  uint32_t n_scores;
  /**
   * Condition number of the feature correlation matrix.
   */
  double condition_number;
  /**
   * Number of low-variance features detected.
   */
  uint32_t n_low_variance;
  /**
   * Number of high-correlation pairs detected.
   */
  uint32_t n_high_corr_pairs;
} CFeatureImportanceResult;

/**
 * C-compatible anomaly detection result (shared by Isolation Forest and LOF).
 */
typedef struct CAnomalyResult {
  /**
   * Anomaly score for each point. Higher = more anomalous.
   * Caller must free with `insight_free_f64_array`.
   */
  double *scores;
  /**
   * Binary anomaly labels (1 = anomaly, 0 = normal).
   * Caller must free with `insight_free_i32_array`.
   */
  int32_t *anomalies;
  /**
   * Number of data points.
   */
  uint32_t n;
  /**
   * Number of anomalies detected.
   */
  uint32_t anomaly_count;
  /**
   * Threshold used for classification.
   */
  double threshold;
} CAnomalyResult;

/**
 * C-compatible correlation result.
 */
typedef struct CCorrelationResult {
  /**
   * Number of variables (n).
   */
  uint32_t n_vars;
  /**
   * Flat n×n correlation matrix (row-major). Caller must free with `insight_free_f64_array`.
   */
  double *matrix;
  /**
   * Number of high-correlation pairs found.
   */
  uint32_t n_high_pairs;
} CCorrelationResult;

/**
 * C-compatible simple regression result.
 */
typedef struct CRegressionResult {
  /**
   * Intercept (β₀).
   */
  double intercept;
  /**
   * Slope (β₁).
   */
  double slope;
  /**
   * R² (coefficient of determination).
   */
  double r_squared;
  /**
   * Adjusted R².
   */
  double adj_r_squared;
  /**
   * P-value for the F-test.
   */
  double f_p_value;
} CRegressionResult;

/**
 * C-compatible Mahalanobis distance result.
 */
typedef struct CMahalanobisResult {
  /**
   * Mahalanobis distances (length = n_rows).
   * Caller must free with `insight_free_f64_array`.
   */
  double *distances;
  /**
   * Anomaly flags (1 = outlier, 0 = normal, length = n_rows).
   * Caller must free with `insight_free_i32_array`.
   */
  int32_t *anomalies;
  /**
   * Number of data points.
   */
  uint32_t n;
  /**
   * Chi-squared threshold used.
   */
  double threshold;
  /**
   * Number of outliers detected.
   */
  uint32_t outlier_count;
} CMahalanobisResult;

/**
 * C-compatible Cramér's V result.
 */
typedef struct CCramersVResult {
  /**
   * Cramér's V (0 to 1).
   */
  double v;
  /**
   * Chi-squared statistic.
   */
  double chi_squared;
  /**
   * P-value.
   */
  double p_value;
} CCramersVResult;

/**
 * C-compatible ANOVA feature result.
 */
typedef struct CAnovaFeature {
  /**
   * Feature index.
   */
  uint32_t index;
  /**
   * F-statistic.
   */
  double f_statistic;
  /**
   * P-value.
   */
  double p_value;
} CAnovaFeature;

/**
 * C-compatible ANOVA selection result.
 */
typedef struct CAnovaSelectionResult {
  /**
   * Per-feature results sorted by p-value ascending.
   * Caller must free with `insight_free_anova_features`.
   */
  struct CAnovaFeature *features;
  /**
   * Number of features.
   */
  uint32_t n_features;
  /**
   * Number of significant features.
   */
  uint32_t n_selected;
} CAnovaSelectionResult;

/**
 * C-compatible hierarchical clustering result.
 */
typedef struct CHierarchicalResult {
  /**
   * Number of flat clusters (0 if no cut).
   */
  uint32_t n_clusters;
  /**
   * Flat cluster labels (length = n_rows). -1 if no labels.
   * Caller must free with `insight_free_i32_array`.
   */
  int32_t *labels;
  /**
   * Number of labels.
   */
  uint32_t n_labels;
  /**
   * Number of merges in the dendrogram.
   */
  uint32_t n_merges;
  /**
   * Merge distances (length = n_merges).
   * Caller must free with `insight_free_f64_array`.
   */
  double *merge_distances;
  /**
   * Merge sizes (length = n_merges).
   * Caller must free with `insight_free_i32_array`.
   */
  int32_t *merge_sizes;
} CHierarchicalResult;

/**
 * C-compatible HDBSCAN result.
 */
typedef struct CHdbscanResult {
  /**
   * Number of clusters found (excluding noise).
   */
  uint32_t n_clusters;
  /**
   * Number of noise points.
   */
  uint32_t noise_count;
  /**
   * Cluster labels (length = n_rows). -1 = noise.
   * Caller must free with `insight_free_i32_array`.
   */
  int32_t *labels;
  /**
   * Membership probabilities (length = n_rows).
   * Caller must free with `insight_free_f64_array`.
   */
  double *probabilities;
  /**
   * Number of data points.
   */
  uint32_t n_labels;
} CHdbscanResult;

/**
 * Result of mutual information feature selection via FFI.
 */
typedef struct CMutualInfoFeature {
  uint32_t index;
  double mi;
} CMutualInfoFeature;

/**
 * Aggregate result for mutual information.
 */
typedef struct CMutualInfoResult {
  struct CMutualInfoFeature *features;
  uint32_t n_features;
} CMutualInfoResult;

/**
 * Result of gap statistic analysis via FFI.
 */
typedef struct CGapStatResult {
  /**
   * Optimal K selected by gap criterion.
   */
  uint32_t best_k;
  /**
   * Number of K values tested.
   */
  uint32_t n_values;
  /**
   * Array of (k, gap) pairs flattened: [k0, gap0, k1, gap1, ...].
   */
  double *gap_values;
  /**
   * Array of (k, stderr) pairs flattened: [k0, se0, k1, se1, ...].
   */
  double *std_errors;
} CGapStatResult;

/**
 * Per-feature permutation importance result via FFI.
 */
typedef struct CPermImportanceFeature {
  uint32_t index;
  double importance;
  double std_dev;
} CPermImportanceFeature;

/**
 * Aggregate permutation importance result via FFI.
 */
typedef struct CPermImportanceResult {
  double baseline_score;
  struct CPermImportanceFeature *features;
  uint32_t n_features;
} CPermImportanceResult;

/**
 * Returns the last error message, or null if no error.
 * The returned string is valid until the next FFI call on this thread.
 *
 * # Safety
 * The caller must not free the returned pointer.
 */
INSIGHT_API const char *insight_last_error(void);

/**
 * Clears the last error message.
 */
INSIGHT_API void insight_clear_error(void);

/**
 * Creates a profile context from a CSV string.
 *
 * # Safety
 * - `csv_data` must be a valid null-terminated UTF-8 string.
 * - The returned handle must be freed with `insight_profile_free`.
 */
INSIGHT_API struct ProfileContext *insight_profile_csv(const char *csv_data);

/**
 * Frees a profile context.
 *
 * # Safety
 * `ctx` must be a valid pointer from `insight_profile_csv`, or null.
 */
INSIGHT_API void insight_profile_free(struct ProfileContext *ctx);

/**
 * Returns the number of rows in the profiled dataset.
 *
 * # Safety
 * `ctx` must be a valid, non-null profile context.
 */
INSIGHT_API int64_t insight_profile_row_count(const struct ProfileContext *ctx);

/**
 * Returns the number of columns in the profiled dataset.
 *
 * # Safety
 * `ctx` must be a valid, non-null profile context.
 */
INSIGHT_API int64_t insight_profile_col_count(const struct ProfileContext *ctx);

/**
 * Gets a summary for a specific column.
 *
 * # Safety
 * `ctx` must be valid. `out` must point to a valid `CColumnSummary`.
 */
INSIGHT_API
int32_t insight_profile_column(const struct ProfileContext *ctx,
                               uint32_t col_idx,
                               struct CColumnSummary *out);

/**
 * Runs K-Means on row-major data.
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values (row-major).
 * - `out` must point to a valid `CKMeansResult`.
 * - The caller must free `out.labels` with `insight_free_labels`.
 */
INSIGHT_API
int32_t insight_kmeans(const double *data,
                       uint32_t n_rows,
                       uint32_t n_cols,
                       uint32_t k,
                       struct CKMeansResult *out);

/**
 * Frees a labels array allocated by `insight_kmeans`.
 *
 * # Safety
 * `labels` must have been allocated by an insight FFI function, or be null.
 */
INSIGHT_API void insight_free_labels(uint32_t *labels, uint32_t count);

/**
 * Runs PCA on row-major data.
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values (row-major).
 * - `out` must point to a valid `CPcaResult`.
 * - Caller must free `out.explained_variance` with `insight_free_f64_array`.
 */
INSIGHT_API
int32_t insight_pca(const double *data,
                    uint32_t n_rows,
                    uint32_t n_cols,
                    uint32_t n_components,
                    int32_t auto_scale,
                    struct CPcaResult *out);

/**
 * Frees an f64 array allocated by an insight FFI function.
 *
 * # Safety
 * `ptr` must have been allocated by an insight FFI function, or be null.
 */
INSIGHT_API void insight_free_f64_array(double *ptr, uint32_t count);

/**
 * Runs DBSCAN on row-major data.
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values (row-major).
 * - `out` must point to a valid `CDbscanResult`.
 * - Caller must free `out.labels` with `insight_free_i32_array`.
 */
INSIGHT_API
int32_t insight_dbscan(const double *data,
                       uint32_t n_rows,
                       uint32_t n_cols,
                       double epsilon,
                       uint32_t min_samples,
                       struct CDbscanResult *out);

/**
 * Frees an i32 array allocated by an insight FFI function.
 *
 * # Safety
 * `ptr` must have been allocated by an insight FFI function, or be null.
 */
INSIGHT_API void insight_free_i32_array(int32_t *ptr, uint32_t count);

/**
 * Runs distribution analysis (normality testing) on a data vector.
 *
 * # Safety
 * - `data` must point to `n` contiguous f64 values.
 * - `out` must point to a valid `CDistributionResult`.
 */
INSIGHT_API
int32_t insight_distribution(const double *data,
                             uint32_t n,
                             double significance_level,
                             struct CDistributionResult *out);

/**
 * Runs feature importance analysis on column-major data.
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values (row-major).
 * - `out` must point to a valid `CFeatureImportanceResult`.
 * - Caller must free `out.scores` with `insight_free_f64_array`.
 */
INSIGHT_API
int32_t insight_feature_importance(const double *data,
                                   uint32_t n_rows,
                                   uint32_t n_cols,
                                   struct CFeatureImportanceResult *out);

/**
 * Runs Isolation Forest anomaly detection on row-major data.
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values (row-major).
 * - `out` must point to a valid `CAnomalyResult`.
 * - Caller must free `out.scores` with `insight_free_f64_array` and
 *   `out.anomalies` with `insight_free_i32_array`.
 */
INSIGHT_API
int32_t insight_isolation_forest(const double *data,
                                 uint32_t n_rows,
                                 uint32_t n_cols,
                                 uint32_t n_estimators,
                                 double contamination,
                                 uint64_t seed,
                                 struct CAnomalyResult *out);

/**
 * Runs Local Outlier Factor anomaly detection on row-major data.
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values (row-major).
 * - `out` must point to a valid `CAnomalyResult`.
 * - Caller must free `out.scores` with `insight_free_f64_array` and
 *   `out.anomalies` with `insight_free_i32_array`.
 */
INSIGHT_API
int32_t insight_lof(const double *data,
                    uint32_t n_rows,
                    uint32_t n_cols,
                    uint32_t k,
                    double threshold,
                    struct CAnomalyResult *out);

/**
 * Computes a Pearson correlation matrix over row-major numeric data.
 *
 * `data`: flat array of `n_rows × n_cols` f64 values, row-major.
 * `out`: pointer to a `CCorrelationResult`.
 *
 * Returns 0 on success, negative on error.
 *
 * # Safety
 * `data` must point to `n_rows * n_cols` f64s. `out` must be valid.
 */
INSIGHT_API
int32_t insight_correlation(const double *data,
                            uint32_t n_rows,
                            uint32_t n_cols,
                            struct CCorrelationResult *out);

/**
 * Computes simple linear regression (one predictor).
 *
 * `x`: predictor array of length `n`.
 * `y`: target array of length `n`.
 * `out`: pointer to a `CRegressionResult`.
 *
 * Returns 0 on success, negative on error.
 *
 * # Safety
 * `x` and `y` must point to `n` f64s. `out` must be valid.
 */
INSIGHT_API
int32_t insight_regression(const double *x,
                           const double *y,
                           uint32_t n,
                           struct CRegressionResult *out);

/**
 * Runs Mahalanobis distance multivariate outlier detection on row-major data.
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values (row-major).
 * - `out` must point to a valid `CMahalanobisResult`.
 * - Caller must free output arrays.
 */
INSIGHT_API
int32_t insight_mahalanobis(const double *data,
                            uint32_t n_rows,
                            uint32_t n_cols,
                            double chi2_quantile,
                            struct CMahalanobisResult *out);

/**
 * Computes Cramér's V for a contingency table.
 *
 * `table`: flat row-major contingency table (observed frequencies).
 *
 * # Safety
 * `table` must point to `n_rows * n_cols` f64s. `out` must be valid.
 */
INSIGHT_API
int32_t insight_cramers_v(const double *table,
                          uint32_t n_rows,
                          uint32_t n_cols,
                          struct CCramersVResult *out);

/**
 * Runs ANOVA F-test feature selection.
 *
 * `data`: row-major n_rows × n_features.
 * `target`: class labels (u32), length n_rows.
 *
 * # Safety
 * All pointers must be valid. Caller frees output.
 */
INSIGHT_API
int32_t insight_anova_select(const double *data,
                             uint32_t n_rows,
                             uint32_t n_features,
                             const uint32_t *target,
                             double significance_level,
                             struct CAnovaSelectionResult *out);

/**
 * Frees ANOVA feature result array.
 *
 * # Safety
 * `ptr` must have been allocated by `insight_anova_select`, or be null.
 */
INSIGHT_API void insight_free_anova_features(struct CAnovaFeature *ptr, uint32_t count);

/**
 * Returns the version string of u-insight.
 *
 * # Safety
 * The returned string is a static string literal. Do not free it.
 */
INSIGHT_API const char *insight_version(void);

/**
 * Runs hierarchical agglomerative clustering on row-major data.
 *
 * # Parameters
 *
 * - `linkage`: 0 = Single, 1 = Complete, 2 = Average, 3 = Ward.
 * - `n_clusters`: Desired number of flat clusters (0 = no cut).
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values.
 * - `out` must point to a valid `CHierarchicalResult`.
 * - Caller must free output arrays with appropriate free functions.
 */
INSIGHT_API
int32_t insight_hierarchical(const double *data,
                             uint32_t n_rows,
                             uint32_t n_cols,
                             uint32_t linkage,
                             uint32_t n_clusters,
                             struct CHierarchicalResult *out);

/**
 * Runs HDBSCAN on row-major data.
 *
 * # Safety
 * - `data` must point to `n_rows * n_cols` contiguous f64 values.
 * - `out` must point to a valid `CHdbscanResult`.
 * - Caller must free output arrays with appropriate free functions.
 */
INSIGHT_API
int32_t insight_hdbscan(const double *data,
                        uint32_t n_rows,
                        uint32_t n_cols,
                        uint32_t min_cluster_size,
                        uint32_t min_samples,
                        struct CHdbscanResult *out);

/**
 * Computes mutual information between continuous features and a categorical target.
 *
 * # Parameters
 * - `data`: row-major feature matrix (n_rows × n_features)
 * - `target`: categorical target array (u32, length n_rows)
 * - `n_bins`: number of bins (0 = auto via Sturges' rule)
 *
 * # Safety
 * Caller must free `out.features` via `insight_free_mi_features`.
 */
INSIGHT_API
int32_t insight_mutual_info(const double *data,
                            uint32_t n_rows,
                            uint32_t n_features,
                            const uint32_t *target,
                            uint32_t n_bins,
                            struct CMutualInfoResult *out);

/**
 * Frees a CMutualInfoFeature array allocated by `insight_mutual_info`.
 *
 * # Safety
 * `ptr` must have been returned by `insight_mutual_info` with matching `count`.
 */
INSIGHT_API void insight_free_mi_features(struct CMutualInfoFeature *ptr, uint32_t count);

/**
 * Runs mini-batch K-Means clustering.
 *
 * # Parameters
 * - `data`: row-major matrix (n_rows × n_cols)
 * - `k`: number of clusters
 * - `batch_size`: mini-batch size (0 = default 100)
 * - `max_iter`: max iterations (0 = default 100)
 * - `seed`: random seed
 *
 * # Safety
 * Caller must free `out.labels` via `insight_free_labels` and
 * `out.centroids` via `insight_free_f64_array(out.centroids, k * n_cols)`.
 */
INSIGHT_API
int32_t insight_mini_batch_kmeans(const double *data,
                                  uint32_t n_rows,
                                  uint32_t n_cols,
                                  uint32_t k,
                                  uint32_t batch_size,
                                  uint32_t max_iter,
                                  uint64_t seed,
                                  struct CKMeansResult *out);

/**
 * Computes gap statistic to find optimal K for clustering.
 *
 * # Parameters
 * - `data`: row-major matrix (n_rows × n_cols)
 * - `k_min`, `k_max`: K range to test
 * - `n_refs`: number of reference datasets
 * - `seed`: random seed
 *
 * # Safety
 * Caller must free `out.gap_values` and `out.std_errors` via
 * `insight_free_f64_array(ptr, n_values * 2)`.
 */
INSIGHT_API
int32_t insight_gap_statistic(const double *data,
                              uint32_t n_rows,
                              uint32_t n_cols,
                              uint32_t k_min,
                              uint32_t k_max,
                              uint32_t n_refs,
                              uint64_t seed,
                              struct CGapStatResult *out);

/**
 * Computes permutation importance for regression features.
 *
 * # Parameters
 * - `data`: row-major feature matrix (n_rows × n_features)
 * - `target`: continuous target array (length n_rows)
 * - `n_repeats`: number of permutation repetitions
 * - `seed`: random seed
 *
 * # Safety
 * Caller must free `out.features` via `insight_free_perm_features`.
 */
INSIGHT_API
int32_t insight_permutation_importance(const double *data,
                                       uint32_t n_rows,
                                       uint32_t n_features,
                                       const double *target,
                                       uint32_t n_repeats,
                                       uint64_t seed,
                                       struct CPermImportanceResult *out);

/**
 * Frees a CPermImportanceFeature array.
 *
 * # Safety
 * `ptr` must have been returned by `insight_permutation_importance` with matching `count`.
 */
INSIGHT_API void insight_free_perm_features(struct CPermImportanceFeature *ptr, uint32_t count);

#endif  /* U_INSIGHT_H */
